export const platforms = [
  {
    name: "YouTube",
    key: "youtube",
    category: "Video",
    description: "Sync YouTube analytics, audience, and revenue data.",
    available: true,
  },
  {
    name: "Twitch",
    key: "twitch",
    category: "Streaming",
    description: "Sync followers, subscriptions, stream activity, and revenue.",
    available: true,
  },
  {
    name: "Kick",
    key: "kick",
    category: "Streaming",
    description: "Sync followers, subscribers, stream activity, and revenue.",
    available: true,
  },
  {
    name: "Shopify",
    key: "shopify",
    category: "Commerce",
    description: "Sync orders, products sold, store revenue, and top products.",
    available: true,
  },
  {
    name: "Patreon",
    key: "patreon",
    category: "Memberships",
    description: "Sync members, tiers, monthly revenue, and member growth.",
    available: true,
  },
  {
    name: "Stripe",
    key: "stripe",
    category: "Payments",
    description: "Sync payments, refunds, net revenue, and payout history.",
    available: true,
  },
  {
    name: "Streamlabs",
    key: "streamlabs",
    category: "Donations",
    description: "Sync donations, tips, top donors, and creator support.",
    available: false,
  },
  {
    name: "StreamElements",
    key: "streamelements",
    category: "Donations",
    description: "Sync donations, overlays, campaigns, and creator support.",
    available: false,
  },
  {
    name: "Fourthwall",
    key: "fourthwall",
    category: "Commerce",
    description: "Sync merch sales, products, orders, and storefront revenue.",
    available: false,
  },
  {
    name: "Gumroad",
    key: "gumroad",
    category: "Digital Products",
    description: "Sync digital product sales, revenue, and customer data.",
    available: false,
  },
];