import {
  SiYoutube,
  SiTwitch,
  SiKick,
  SiShopify,
  SiPatreon,
  SiStripe,
  SiPaypal,
} from "react-icons/si";

const platformRegistry = [
  {
    key: "youtube",
    name: "YouTube",
    category: "Video",
    description: "Sync YouTube analytics, audience, and revenue data.",
    available: true,
    icon: SiYoutube,
    brandColor: "#FF0000",
    connectRoute: "/api/auth/google/start",
    detailRoute: "/platforms/youtube",

    externalDashboard: {
      label: "Open YouTube Studio",
      href: "https://studio.youtube.com",
    },

    intelligenceAvailable: true,
    supportsMultipleAccounts: true,
    connectionLabel: "Channel",
    connectionLabelPlural: "Channels",
    domains: ["revenue", "audience", "content"],

    detailSections: [
      {
        key: "overview",
        label: "Overview",
        description:
          "Review YouTube’s most important performance, audience, and revenue signals.",
        importance: "primary",
        layout: "full",
        defaultExpanded: true,
      },
      {
        key: "content",
        label: "Content Performance",
        description:
          "Understand which videos, Shorts, and live streams are driving results.",
        importance: "primary",
        layout: "full",
        defaultExpanded: true,
      },
      {
        key: "audience",
        label: "Audience",
        description:
          "Track viewer growth, returning viewers, subscribers, and audience behavior.",
        importance: "primary",
        layout: "full",
        defaultExpanded: true,
      },
      {
        key: "revenue",
        label: "Revenue",
        description:
          "Review advertising, memberships, Supers, and other YouTube earnings.",
        importance: "primary",
        layout: "full",
        defaultExpanded: true,
      },
      {
        key: "reach",
        label: "Reach",
        description:
          "Review impressions, click-through rate, discovery, and content reach.",
        importance: "supporting",
        layout: "half",
        defaultExpanded: false,
      },
      {
        key: "engagement",
        label: "Engagement",
        description:
          "Track watch time, likes, comments, shares, and audience interaction.",
        importance: "supporting",
        layout: "half",
        defaultExpanded: false,
      },
      {
        key: "traffic",
        label: "Traffic Sources",
        description:
          "Understand how viewers discover your content across YouTube and external sources.",
        importance: "supporting",
        layout: "half",
        defaultExpanded: false,
      },
      {
        key: "retention",
        label: "Viewer Retention",
        description:
          "Identify where viewers stay engaged, lose interest, or leave your content.",
        importance: "supporting",
        layout: "half",
        defaultExpanded: false,
      },
    ],
  },
  {
    key: "twitch",
    name: "Twitch",
    category: "Streaming",
    description: "Sync followers, subscriptions, stream activity, and revenue.",
    available: true,
    icon: SiTwitch,
    brandColor: "#9146FF",
    connectRoute: "/api/auth/twitch/start",
    detailRoute: "/platforms/twitch",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Channel",
    connectionLabelPlural: "Channels",
    domains: ["revenue", "audience", "content", "community"],
  },
  {
    key: "kick",
    name: "Kick",
    category: "Streaming",
    description: "Sync followers, subscribers, stream activity, and revenue.",
    available: true,
    icon: SiKick,
    brandColor: "#53FC18",
    connectRoute: "/api/auth/kick/start",
    detailRoute: "/platforms/kick",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Channel",
    connectionLabelPlural: "Channels",
    domains: ["revenue", "audience", "content", "community"],
  },
  {
    key: "shopify",
    name: "Shopify",
    category: "Commerce",
    description: "Sync orders, products sold, store revenue, and top products.",
    available: true,
    icon: SiShopify,
    brandColor: "#95BF47",
    connectRoute: "/api/auth/shopify/start",
    detailRoute: "/platforms/shopify",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Store",
    connectionLabelPlural: "Stores",
    domains: ["revenue", "commerce"],
  },
  {
    key: "patreon",
    name: "Patreon",
    category: "Memberships",
    description: "Sync members, tiers, monthly revenue, and member growth.",
    available: true,
    icon: SiPatreon,
    brandColor: "#FF424D",
    connectRoute: "/api/auth/patreon/start",
    detailRoute: "/platforms/patreon",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Creator Page",
    connectionLabelPlural: "Creator Pages",
    domains: ["revenue", "community"],
  },
  {
    key: "stripe",
    name: "Stripe",
    category: "Payments",
    description: "Sync payments, refunds, net revenue, and payout history.",
    available: true,
    icon: SiStripe,
    brandColor: "#635BFF",
    connectRoute: "/api/auth/stripe/start",
    detailRoute: "/platforms/stripe",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "commerce"],
  },
  {
    key: "paypal",
    name: "PayPal",
    category: "Payments",
    description: "Sync direct payments, sponsor payments, refunds, and creator income.",
    available: true,
    icon: SiPaypal,
    brandColor: "#003087",
    connectRoute: "/api/auth/paypal/start",
    detailRoute: "/platforms/paypal",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "sponsorships"],
  },
  {
    key: "streamlabs",
    name: "Streamlabs",
    category: "Donations",
    description: "Sync donations, tips, top donors, and creator support.",
    available: true,
    icon: null,
    brandColor: "#80F5D2",
    connectRoute: "/api/auth/streamlabs/start",
    detailRoute: "/platforms/streamlabs",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "community"],
  },
  {
    key: "streamelements",
    name: "StreamElements",
    category: "Donations",
    description: "Sync donations, overlays, campaigns, and creator support.",
    available: true,
    icon: null,
    brandColor: "#5B7CFF",
    connectRoute: "/api/auth/streamelements/start",
    detailRoute: "/platforms/streamelements",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "community"],
  },
  {
    key: "fourthwall",
    name: "Fourthwall",
    category: "Commerce",
    description: "Sync merch sales, products, orders, and storefront revenue.",
    available: false,
    icon: null,
    brandColor: null,
    connectRoute: null,
    detailRoute: "/platforms/fourthwall",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Store",
    connectionLabelPlural: "Stores",
    domains: ["revenue", "commerce"],
  },
  {
    key: "gumroad",
    name: "Gumroad",
    category: "Digital Products",
    description: "Sync digital product sales, revenue, and customer data.",
    available: false,
    icon: null,
    brandColor: "#FF90E8",
    connectRoute: null,
    detailRoute: "/platforms/gumroad",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Store",
    connectionLabelPlural: "Stores",
    domains: ["revenue", "commerce"],
  },
];

export const platforms = platformRegistry;

export function getPlatform(platformKey) {
  return platformRegistry.find((platform) => platform.key === platformKey) || null;
}

export function getAvailablePlatforms() {
  return platformRegistry.filter((platform) => platform.available);
}