import {
  SiYoutube,
  SiTwitch,
  SiKick,
  SiShopify,
  SiPatreon,
  SiStripe,
  SiPaypal,
} from "react-icons/si";

const platformRegistry = [
  {
    key: "youtube",
    name: "YouTube",
    category: "Video",
    description: "Sync YouTube analytics, audience, and revenue data.",
    available: true,
    icon: SiYoutube,
    brandColor: "#FF0000",
    connectRoute: "/api/auth/google/start",
    detailRoute: "/platforms/youtube",
    intelligenceAvailable: true,
    supportsMultipleAccounts: true,
    connectionLabel: "Channel",
    connectionLabelPlural: "Channels",
    domains: ["revenue", "audience", "content"],
  },
  {
    key: "twitch",
    name: "Twitch",
    category: "Streaming",
    description: "Sync followers, subscriptions, stream activity, and revenue.",
    available: true,
    icon: SiTwitch,
    brandColor: "#9146FF",
    connectRoute: "/api/auth/twitch/start",
    detailRoute: "/platforms/twitch",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Channel",
    connectionLabelPlural: "Channels",
    domains: ["revenue", "audience", "content", "community"],
  },
  {
    key: "kick",
    name: "Kick",
    category: "Streaming",
    description: "Sync followers, subscribers, stream activity, and revenue.",
    available: true,
    icon: SiKick,
    brandColor: "#53FC18",
    connectRoute: "/api/auth/kick/start",
    detailRoute: "/platforms/kick",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Channel",
    connectionLabelPlural: "Channels",
    domains: ["revenue", "audience", "content", "community"],
  },
  {
    key: "shopify",
    name: "Shopify",
    category: "Commerce",
    description: "Sync orders, products sold, store revenue, and top products.",
    available: true,
    icon: SiShopify,
    brandColor: "#95BF47",
    connectRoute: "/api/auth/shopify/start",
    detailRoute: "/platforms/shopify",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Store",
    connectionLabelPlural: "Stores",
    domains: ["revenue", "commerce"],
  },
  {
    key: "patreon",
    name: "Patreon",
    category: "Memberships",
    description: "Sync members, tiers, monthly revenue, and member growth.",
    available: true,
    icon: SiPatreon,
    brandColor: "#FF424D",
    connectRoute: "/api/auth/patreon/start",
    detailRoute: "/platforms/patreon",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Creator Page",
    connectionLabelPlural: "Creator Pages",
    domains: ["revenue", "community"],
  },
  {
    key: "stripe",
    name: "Stripe",
    category: "Payments",
    description: "Sync payments, refunds, net revenue, and payout history.",
    available: true,
    icon: SiStripe,
    brandColor: "#635BFF",
    connectRoute: "/api/auth/stripe/start",
    detailRoute: "/platforms/stripe",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "commerce"],
  },
  {
    key: "paypal",
    name: "PayPal",
    category: "Payments",
    description: "Sync direct payments, sponsor payments, refunds, and creator income.",
    available: true,
    icon: SiPaypal,
    brandColor: "#003087",
    connectRoute: "/api/auth/paypal/start",
    detailRoute: "/platforms/paypal",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "sponsorships"],
  },
  {
    key: "streamlabs",
    name: "Streamlabs",
    category: "Donations",
    description: "Sync donations, tips, top donors, and creator support.",
    available: true,
    icon: null,
    brandColor: "#80F5D2",
    connectRoute: "/api/auth/streamlabs/start",
    detailRoute: "/platforms/streamlabs",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "community"],
  },
  {
    key: "streamelements",
    name: "StreamElements",
    category: "Donations",
    description: "Sync donations, overlays, campaigns, and creator support.",
    available: true,
    icon: null,
    brandColor: "#5B7CFF",
    connectRoute: "/api/auth/streamelements/start",
    detailRoute: "/platforms/streamelements",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Account",
    connectionLabelPlural: "Accounts",
    domains: ["revenue", "community"],
  },
  {
    key: "fourthwall",
    name: "Fourthwall",
    category: "Commerce",
    description: "Sync merch sales, products, orders, and storefront revenue.",
    available: false,
    icon: null,
    brandColor: null,
    connectRoute: null,
    detailRoute: "/platforms/fourthwall",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Store",
    connectionLabelPlural: "Stores",
    domains: ["revenue", "commerce"],
  },
  {
    key: "gumroad",
    name: "Gumroad",
    category: "Digital Products",
    description: "Sync digital product sales, revenue, and customer data.",
    available: false,
    icon: null,
    brandColor: "#FF90E8",
    connectRoute: null,
    detailRoute: "/platforms/gumroad",
    intelligenceAvailable: false,
    supportsMultipleAccounts: true,
    connectionLabel: "Store",
    connectionLabelPlural: "Stores",
    domains: ["revenue", "commerce"],
  },
];

export const platforms = platformRegistry;

export function getPlatform(platformKey) {
  return platformRegistry.find((platform) => platform.key === platformKey) || null;
}

export function getAvailablePlatforms() {
  return platformRegistry.filter((platform) => platform.available);
}