import { buildPlatformToday } from "@/lib/business/buildPlatformToday";
import { buildRecommendedNextAction } from "@/lib/business/buildRecommendedNextAction";
import { getPlatform } from "@/lib/platforms";

const youtubeConfig = getPlatform("youtube");

export const youtubePlatformDetail = {
  key: youtubeConfig.key,
  name: youtubeConfig.name,
  type: youtubeConfig.category,
  status: "healthy",
  accountName: "@creatorchannel",
  lastSynced: "2 min ago",
  lastSyncedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),

  brief: {
    whatHappened: "Your newest upload is outperforming your recent average.",
    whyItMatters:
      "Views are growing faster than subscriber growth, which means more new viewers are discovering your content.",
    recommendation:
      "Publish another long-form video within the next 48 hours while momentum is elevated.",
  },

  keyMetrics: [
    { label: "Revenue Today", value: "$148", trend: "+15%" },
    { label: "Views Today", value: "31.4K", trend: "+12%" },
    { label: "Subscribers", value: "+412", trend: "+8%" },
    { label: "Watch Time", value: "940h", trend: "+14%" },
  ],

  reasons: [
    "Returning viewers increased after your latest upload.",
    "Click-through rate stayed above your recent average.",
    "Watch time improved, which may help the video continue reaching new viewers.",
  ],

  contentPerformance: [
    {
      label: "Top Recent Video",
      title: "How I Built My Creator Store",
      metric: "18.4K views today",
    },
    {
      label: "Most Improved",
      title: "Behind the Scenes: Product Launch",
      metric: "+42% watch time",
    },
    {
      label: "Needs Review",
      title: "Weekly Update #12",
      metric: "CTR below average",
    },
  ],

  reachMetrics: [
    {
      label: "Impressions",
      value: "284K",
      trend: "+16%",
      detail: "How often YouTube displayed your thumbnails to potential viewers.",
    },
    {
      label: "Impressions CTR",
      value: "6.8%",
      trend: "+0.7%",
      detail: "The percentage of impressions that became video views.",
    },
    {
      label: "Unique Viewers",
      value: "24.9K",
      trend: "+11%",
      detail: "Estimated individual viewers reached during this period.",
    },
  ],

  engagementMetrics: [
    {
      label: "Average View Duration",
      value: "8m 42s",
      trend: "+9%",
      detail: "The average amount of time viewers spent watching each view.",
    },
    {
      label: "Likes",
      value: "2.8K",
      trend: "+13%",
      detail: "Viewer likes recorded across recent content.",
    },
    {
      label: "Comments",
      value: "486",
      trend: "+6%",
      detail: "Comments generated by recent uploads and live content.",
    },
    {
      label: "Shares",
      value: "214",
      trend: "+18%",
      detail: "The number of times viewers shared your content.",
    },
  ],

  trafficSourceMetrics: [
    {
      label: "Browse Features",
      value: "38%",
      trend: "+5%",
      detail: "Views originating from Home, subscriptions, Watch Later, and other browse surfaces.",
    },
    {
      label: "Suggested Videos",
      value: "27%",
      trend: "+8%",
      detail: "Views generated when YouTube recommended your content beside or after another video.",
    },
    {
      label: "YouTube Search",
      value: "19%",
      trend: "-2%",
      detail: "Views generated through viewer searches on YouTube.",
    },
    {
      label: "External Sources",
      value: "9%",
      trend: "+3%",
      detail: "Views arriving from websites, social platforms, and embedded videos.",
    },
  ],

  retentionMetrics: [
    {
      label: "Average Percentage Viewed",
      value: "54%",
      trend: "+6%",
      detail: "The average percentage of each video viewers watched.",
    },
    {
      label: "First 30 Seconds",
      value: "72%",
      trend: "+4%",
      detail: "The share of viewers who remained after the opening 30 seconds.",
    },
    {
      label: "Midpoint Retention",
      value: "48%",
      trend: "+3%",
      detail: "The share of viewers still watching halfway through the content.",
    },
    {
      label: "End Screen Reach",
      value: "31%",
      trend: "-1%",
      detail: "The share of viewers who reached the final portion of the video.",
    },
  ],

  audienceMetrics: [
    { label: "Returning Viewers", value: "12.8K", trend: "+18%" },
    { label: "New Viewers", value: "18.6K", trend: "+9%" },
    { label: "Subscriber Growth", value: "+412", trend: "+8%" },
  ],

  revenueMetrics: [
    { label: "Ad Revenue", value: "$96", trend: "+11%" },
    { label: "Memberships", value: "$34", trend: "+7%" },
    { label: "Supers", value: "$18", trend: "+22%" },
  ],
};

export const youtubePlatformToday = buildPlatformToday({
  platformName: youtubePlatformDetail.name,
  status: youtubePlatformDetail.status,
  accountName: youtubePlatformDetail.accountName,
  lastSyncedAt: youtubePlatformDetail.lastSyncedAt,
  lastSyncedLabel: youtubePlatformDetail.lastSynced,

  headline: youtubePlatformDetail.brief.whatHappened,
  summary: youtubePlatformDetail.brief.whyItMatters,
  recommendation: youtubePlatformDetail.brief.recommendation,

  action: {
    label: "Review Content Performance",
    href: "#content-performance",
  },

  metrics: youtubePlatformDetail.keyMetrics,
  reasons: youtubePlatformDetail.reasons,
});

export const youtubeRecommendedNextAction =
  buildRecommendedNextAction({
    source: "platform",

    platform: {
      key: youtubePlatformDetail.key,
      name: youtubePlatformDetail.name,
    },

    revenueSummary: {
      monthlyGrowthPercent: 22,
    },

    businessSignals: [],
  });